import { useState } from 'react';
import { CaseTask, CaseSchedule } from '../types';
import { CaseEvent } from '../../timeline/types';

export const useTasksData = () => {
  const [tasks, setTasks] = useState<CaseTask[]>([
    {
      id: '1',
      caseId: '1',
      caseName: 'Покупка квартиры на Арбате',
      clientName: 'Иван Петров',
      title: 'Подготовить исковое заявление',
      description: 'Составить исковое заявление о признании права собственности на квартиру. Включить все необходимые документы и обоснования.',
      status: 'completed',
      priority: 'high',
      assignedTo: 'anna_petrova',
      assignedBy: 'mikhail_sokolov',
      assignedAt: '2024-08-20T09:00:00Z',
      targetRole: 'coordinator',
      dueDate: '2024-08-27T17:00:00Z',
      completedAt: '2024-08-27T10:30:00Z',
      estimatedHours: 4,
      actualHours: 3.5,
      progress: 100,
      result: {
        status: 'success',
        summary: 'Исковое заявление подготовлено в полном объёме, все документы проверены',
        deliverables: ['Исковое заявление', 'Пакет документов', 'Обоснование позиции'],
        timeSpent: 210
      },
      autoCreateEvent: true,
      timelineEventId: '1',
      tags: ['документы', 'исковое', 'срочно'],
      createdBy: 'mikhail_sokolov'
    },
    {
      id: '2',
      caseId: '1',
      caseName: 'Покупка квартиры на Арбате',
      clientName: 'Иван Петров',
      title: 'Подать документы в суд',
      description: 'Подать исковое заявление и пакет документов в Арбитражный суд города Москвы. Получить входящий номер дела.',
      status: 'completed',
      priority: 'high',
      assignedTo: 'anna_petrova',
      assignedBy: 'mikhail_sokolov',
      assignedAt: '2024-08-27T11:00:00Z',
      targetRole: 'litigator',
      startDate: '2024-08-28T09:00:00Z',
      dueDate: '2024-08-28T17:00:00Z',
      completedAt: '2024-08-26T14:15:00Z',
      estimatedHours: 2,
      actualHours: 1.5,
      progress: 100,
      dependencies: ['1'],
      result: {
        status: 'success',
        summary: 'Документы поданы успешно, получен номер дела А40-123456/24',
        deliverables: ['Номер дела', 'Уведомление о принятии'],
        nextSteps: ['Подготовиться к предварительному заседанию'],
        timeSpent: 90
      },
      autoCreateEvent: true,
      timelineEventId: '2',
      tags: ['суд', 'подача', 'документы'],
      createdBy: 'mikhail_sokolov'
    },
    {
      id: '3',
      caseId: '2',
      caseName: 'Корпоративные договоры ООО "Строй-Инвест"',
      clientName: 'Мария Сидорова',
      title: 'Подготовиться к судебному заседанию',
      description: 'Изучить материалы дела, подготовить выступление, собрать дополнительные доказательства для арбитражного заседания.',
      status: 'completed',
      priority: 'critical',
      assignedTo: 'mikhail_sokolov',
      assignedBy: 'mikhail_sokolov',
      assignedAt: '2024-08-20T14:00:00Z',
      targetRole: 'litigator',
      startDate: '2024-08-21T09:00:00Z',
      dueDate: '2024-08-23T09:00:00Z',
      completedAt: '2024-08-22T18:00:00Z',
      estimatedHours: 6,
      actualHours: 8,
      progress: 100,
      result: {
        status: 'success',
        summary: 'Подготовка завершена, все материалы изучены, позиция сформирована',
        deliverables: ['План выступления', 'Дополнительные доказательства', 'Правовая позиция'],
        timeSpent: 480
      },
      autoCreateEvent: true,
      timelineEventId: '5',
      tags: ['суд', 'подготовка', 'критично'],
      createdBy: 'mikhail_sokolov'
    },
    {
      id: '4',
      caseId: '2',
      caseName: 'Корпоративные договоры ООО "Строй-Инвест"',
      clientName: 'Мария Сидорова',
      title: 'Получить исполнительный лист',
      description: 'После вступления решения суда в силу получить исполнительный лист для принудительного взыскания.',
      status: 'pending',
      priority: 'high',
      assignedTo: 'elena_krasnova',
      assignedBy: 'mikhail_sokolov',
      assignedAt: '2024-08-23T15:00:00Z',
      targetRole: 'assistant',
      startDate: '2024-09-05T09:00:00Z',
      dueDate: '2024-09-10T17:00:00Z',
      estimatedHours: 1,
      progress: 0,
      autoCreateEvent: true,
      tags: ['исполнительный', 'лист', 'взыскание'],
      createdBy: 'mikhail_sokolov'
    },
    {
      id: '5',
      caseId: '3',
      caseName: 'Семейный спор Коваленко',
      clientName: 'Алексей Коваленко',
      title: 'Подготовить отзыв на иск',
      description: 'Составить отзыв на исковое заявление супруги, подготовить возражения и встречные требования.',
      status: 'in_progress',
      priority: 'high',
      assignedTo: 'elena_krasnova',
      assignedBy: 'mikhail_sokolov',
      assignedAt: '2024-08-24T16:00:00Z',
      targetRole: 'coordinator',
      startDate: '2024-08-25T09:00:00Z',
      dueDate: '2024-08-30T17:00:00Z',
      estimatedHours: 5,
      actualHours: 3,
      progress: 60,
      autoCreateEvent: true,
      tags: ['отзыв', 'семейное', 'возражения'],
      createdBy: 'mikhail_sokolov'
    },
    {
      id: '6',
      caseId: '1',
      caseName: 'Покупка квартиры на Арбате',
      clientName: 'Иван Петров',
      title: 'Подготовить отчёт для клиента',
      description: 'Составить подробный отчёт о ходе дела для клиента, включить все достигнутые результаты и следующие шаги.',
      status: 'overdue',
      priority: 'medium',
      assignedTo: 'anna_petrova',
      assignedBy: 'mikhail_sokolov',
      assignedAt: '2024-08-25T10:00:00Z',
      targetRole: 'coordinator',
      dueDate: '2024-08-26T17:00:00Z',
      estimatedHours: 2,
      progress: 25,
      autoCreateEvent: false,
      tags: ['отчёт', 'клиент', 'информирование'],
      createdBy: 'mikhail_sokolov'
    }
  ]);

  const [schedules, setSchedules] = useState<CaseSchedule[]>([
    {
      id: '1',
      caseId: '1',
      caseName: 'Покупка квартиры на Арбате',
      clientName: 'Иван Петров',
      coordinatorId: 'mikhail_sokolov',
      coordinatorName: 'Михаил Соколов',
      status: 'active',
      startDate: '2024-08-20T00:00:00Z',
      expectedEndDate: '2024-09-30T23:59:59Z',
      totalTasks: 0,
      completedTasks: 0,
      overdueTasks: 0,
      progress: 0,
      createdAt: '2024-08-20T09:00:00Z',
      updatedAt: '2024-08-27T12:00:00Z'
    },
    {
      id: '2',
      caseId: '2',
      caseName: 'Корпоративные договоры ООО "Строй-Инвест"',
      clientName: 'Мария Сидорова',
      coordinatorId: 'mikhail_sokolov',
      coordinatorName: 'Михаил Соколов',
      status: 'active',
      startDate: '2024-08-15T00:00:00Z',
      expectedEndDate: '2024-10-15T23:59:59Z',
      totalTasks: 0,
      completedTasks: 0,
      overdueTasks: 0,
      progress: 0,
      createdAt: '2024-08-15T09:00:00Z',
      updatedAt: '2024-08-23T15:30:00Z'
    },
    {
      id: '3',
      caseId: '3',
      caseName: 'Семейный спор Коваленко',
      clientName: 'Алексей Коваленко',
      coordinatorId: 'mikhail_sokolov',
      coordinatorName: 'Михаил Соколов',
      status: 'active',
      startDate: '2024-08-24T00:00:00Z',
      expectedEndDate: '2024-11-30T23:59:59Z',
      totalTasks: 0,
      completedTasks: 0,
      overdueTasks: 0,
      progress: 0,
      createdAt: '2024-08-24T10:00:00Z',
      updatedAt: '2024-08-24T16:30:00Z'
    }
  ]);

  const [timelineEvents, setTimelineEvents] = useState<CaseEvent[]>([]);

  return {
    tasks,
    setTasks,
    schedules,
    setSchedules,
    timelineEvents,
    setTimelineEvents
  };
};